Database:
   Tipo: SQLITE #Tipos: MYSQL, SQLITE, MYSQL_FAST
   IP: localhost:3306
   DB: test
   User: admin
   Pass: ''
   Debug: true

Comando:
   Comando: 'tags'
   Aliases: [tag]

#Coloque Legendchat, OpeNChat (ou nChat), UltimateChat, NoxusChat ou deixe Automatico para o auto-detect
Plugin de chat: 'Automatico'

Tag propria:
   Chat: true
   Placeholder: true
   
Mensagens:
   Permissao: '&c&lERRO! &cVocê não tem permissão para isto.'
   Nao tem pontos: '&cDesculpe, mas você não possui a quantia necessária de pontos, &7{pontos} pontos&c.'
   Nao tem money: '&cDesculpe, mas você não possui a quantia necessária de money, &7{money} money&c.'
   Comprou: '&aObrigado pela sua compra, você adquiriu 1x &7Tag ( {tag} &7)&a com sucesso.'
   Nao encontrado: '&c&lERRO! &cJogador não encontrado.'
   Setada: '&a&lSUCESSO! &aVocê setou a tag do jogador &7{player} &apara &7{tag}&a.'
   Limpa: '&a&lSUCESSO! &aVocê limpou a tag do jogador &7{player}&a.'
   Recebeu: '&aVocê recebeu um vale-tag da tag &7{tag}&a.'
   Ativou: '&aVocê ativou um vale-tag da tag &7{tag}&a.'
   Ja tem: '&c&lERRO! &cVocê já possui esta tag.'
   Ja tem player: '&c&lERRO! &cEste jogador já possui esta tag.'
   Deu: '&aVocê deu um vale-tag da tag &7{tag}&a para o jogador &7{player}&a.'
   Adicionou: '&aVocê adicionou a tag &7{tag}&a para o jogador &7{player}&a.'
   Deu pacote: '&aVocê deu um pacote de tags &7{pacote}&a para o jogador &7{player}&a.'
   Recebeu pacote: '&aVocê recebeu um pacote de tags &7{pacote}&a.'
   Ja tem todas: '&c&lERRO! &cVocê já possui todas as tags deste pacote.'
   Ativou pacote: '&aVocê ativou um pacote de tags &7{pacote}&a.'
   Permissao tag: '&cVocê não pode usar esta tag.'
   Nao tem player: '&c&lERRO! &cEste jogador não possui esta tag.'
   Removeu: '&aVocê removeu a tag &7{tag}&a do jogador &7{player}&a.'
   Equipou player: '&aVocê forçou equipar a tag &7{tag}&a para o jogador &7{player}&a.'
   Info:
   - ''
   - '&aInformações do jogador &7{player}&a:'
   - '&f > &bTag equipada: &7{tag}&f.'
   - '&f > &bTag própria: &7{owntag}&f.'
   - ''
   Comandos:
   - ''
   - '&aLista de comandos:'
   - '&f > /tag &8&l- &7Abre o menu principal.'
   - '&f > /tag cash &8&l- &7Abre o menu de tags por cash.'
   - '&f > /tag money &8&l- &7Abre o menu de tags por money.'
   - '&f > /tag info &f<player> &8&l- &7Vê as informações de um jogador.'
   - '&f > /tag setar &f<player> <tag> &8&l- &7Seta uma tag customizada à um jogador.'
   - '&f > /tag limpar &f<player> &8&l- &7Limpa a tag customizada de um jogador.'
   - '&f > /tag add &f<player> <tag> &8&l- &7Adiciona uma tag à um jogador.'
   - '&f > /tag dar &f<player> <tag> &8&l- &7Da uma tag em forma de item à um jogador.'
   - '&f > /tag darpacote &f<player> <pacote> &8&l- &7Da um pacote de tags em forma de item à um jogador.'
   - ''
   
Vale tag:
   CustomSkull: false
   URL: ''
   ID: NAME_TAG
   Data: 0
   Glow: true
   Name: '&aVale Tag &8&l- &7{tag}'
   Lore:
   - '&7Tag: &f{tag}&7.'
   - ''
   - '&7Clique com botão direito para ativar.'
         
Setas:
   Voltar:
      CustomSkull: false
      URL: ''
      ID: ARROW
      Data: 0
      Glow: true
      Name: '&cVoltar'
      Lore:
      - '&7Clique para voltar ao menu ou página anterior.'
   Proximo:
      CustomSkull: false
      URL: ''
      ID: ARROW
      Data: 0
      Glow: true
      Name: '&aPróxima'
      Lore:
      - '&7Clique para ir à próxima página.'
      
Lores:
   Equipar:
      Sobrepor: true
      Lore:
      - '&7Clique para equipar esta tag.'
   Desequipar:
      Sobrepor: true
      Lore:
      - '&7Clique para desequipar esta tag.'
      
Formats:
 - ''
 - ''
 - 'K'
 - 'M'
 - 'B'
 - 'T'
 - 'Q'
 - 'QQ'
 - 'S'
 - 'SS'
 - 'O'
 - 'N'
 - 'D'